kind: Pod
apiVersion: v1
metadata:
  name: pod1
spec:
  affinity: 
    nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            matchExpressions:
              key: type
              operator: eq    
              values:
               - t2.micro
  containers:
   - name: master-container
     image: wlan0/postgresql-master:v0.1
     volumeMounts:
      - mountPath: /postgresql
        name: masterPV

